#!/usr/bin/env node
'use strict';

let crx = require('./index')
let u = crx.u
let argv = process.argv

function main() {
    if (argv.length !== 2+2)
	u.err(`Usage: ${u.progname()} rsa public.pem < file.zip`)

    u.read().then(crx.parse).then(verify).catch(u.err)
}

function verify(hdr) {
    if (argv[2] !== 'rsa') throw new Error(`no support for ${argv[2]}`)

    return u.read(argv[3]).then(crx.pem2der).then( key => {
	if (!crx.verify_rsa(key, hdr.signed_header_data.crx_id))
	    process.exitCode = 1
    })
}

main()
