#!/usr/bin/env node
'use strict';

let crx = require('./index')
let u = crx.u

async function main() {
    if (!process.argv[2]) u.err(`Usage: ${u.progname()} private.pem < file.zip`)

    let [kp, zip] = await Promise.all([crx.keypair(process.argv[2]), u.read()])
	.catch(u.err)

    let maker = new crx.Maker(kp, zip)
    process.stdout.write(maker.creat())
}

main()
